package com.hubin.android.p2pvoice.bean.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pointerDaoConfig;

    private final PointerDao pointerDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pointerDaoConfig = daoConfigMap.get(PointerDao.class).clone();
        pointerDaoConfig.initIdentityScope(type);

        pointerDao = new PointerDao(pointerDaoConfig, this);

        registerDao(Pointer.class, pointerDao);
    }
    
    public void clear() {
        pointerDaoConfig.getIdentityScope().clear();
    }

    public PointerDao getPointerDao() {
        return pointerDao;
    }

}
